knownProgrammer/knownProgrammer/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts.views.function_based_views import (
    homepage,
)

urlpatterns = [
    path('', homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('programmers/', include('programmers.urls_programmers')),
    path('accounts/', include('accounts.urls_accounts')),
    path('messages/', include('communication.urls_communication'))
]

knownProgrammer/programmers/models.py
from django.conf import settings

from django.db import models
from multiselectfield import MultiSelectField


class ProgrammerProfile(models.Model):
    EXP = {
        ("Junior", "Junior"),
        ("Mid", "Mid"),
        ("Senior", "Senior"),
    }

    CODE = (
        ("JavaScript", "JavaScript"),
        ("Python", "Python"),
        ("Java", "Java"),
        ("C", "C"),
        ("C++", "C++"),
        ("C#", "C#"),
        ("R", "R"),
        ("PHP", "PHP"),
        ("SQL", "SQL"),
        ("RUST", "RUST"),
        ("Kotlin", "Kotlin"),
        ("HTML", "HTML"),
        ("CSS", "CSS"),
        ("TypeScript", "TypeScript"),
        ("Scala", "Scala"),
        ("SWIFT", "SWIFT"),

    )

    TECH_STACK = (
        ("Django", "Django"),
        ("Celery", "Celery"),
        ("Flask", "Flask"),
        ("FastAPI", "FastAPI"),
        ("Databases", "Databases"),
        ("Docker", "Docker"),
        ("Git | GitHub", "Git | GitHub"),
        ("Node.js", "Node.js"),
        ("React", "React"),
        ("Symphony", "Symphony"),
        ("Ruby on Rails", "Ruby on Rails"),
    )

    user_id = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                   related_name='programmer_profile')
    wage = models.PositiveIntegerField()
    description = models.TextField(max_length=5000)
    experience = models.CharField(max_length=100, choices=EXP)
    portfolio = models.URLField(max_length=1000)
    programming_languages = MultiSelectField(choices=CODE, max_length=500)
    tech_stack = MultiSelectField(choices=TECH_STACK, max_length=500)
    phone = models.CharField(max_length=11, unique=True, null=True, blank=True)

    def __str__(self):
        return f"Programmer profile of {self.user_id.email} ({self.user_id.first_name} {self.user_id.last_name})"

    def average_rating(self):
        ratings = self.ratings.all()
        if ratings:
            total_ratings = sum(r.rating for r in ratings)
            avg = total_ratings / len(ratings)
            return avg.__round__(2)
        else:
            return 0

    def ratings_count(self):
        return self.ratings.count()

    def is_rated(self, user):
        return self.ratings.filter(user=user).exists()

    @classmethod
    def get_profile_by_user_id(cls, user_id):
        try:
            return cls.objects.get(user_id=user_id)
        except ProgrammerProfile.DoesNotExist:
            return None


class Rating(models.Model):
    programmer = models.ForeignKey(ProgrammerProfile, related_name='ratings', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='ratings_given', on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()

    def __str__(self):
        return f"Rating for {self.programmer.user_id.email} by {self.user_id.email}"

knownProgrammer/programmers/forms.py
from django import forms
from django.core.exceptions import ValidationError

from programmers.models import ProgrammerProfile


class ProgrammerCreationModelForm(forms.ModelForm):
    class Meta:
        model = ProgrammerProfile
        fields = ['description', 'experience', 'programming_languages', 'tech_stack', 'wage',
                  'portfolio', 'phone']

    def clean_wage(self):
        wage = self.cleaned_data["wage"]
        if wage <= 0:
            raise ValidationError("Wage must be bigger than zero")
        return wage

    def save(self, commit=True):
        programmer = super(ProgrammerCreationModelForm, self).save(commit=False)
        if commit:
            programmer.save()
        if self.cleaned_data['programming_languages']:
            programmer.programming_languages = self.cleaned_data['programming_languages']
        return programmer


class RatingForm(forms.Form):
    RATING_CHOICES = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    ]
    rating = forms.ChoiceField(choices=RATING_CHOICES, widget=forms.RadioSelect)


class AvatarUploadForm(forms.Form):
    avatar = forms.ImageField()

knownProgrammer/programmers/views.py
import cloudinary
import cloudinary.uploader
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseNotFound, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView

from accounts.models import CustomUser, DEFAULT_AVATAR
from programmers.filters import ProgrammerFilter
from programmers.forms import ProgrammerCreationModelForm, RatingForm, AvatarUploadForm
from programmers.models import ProgrammerProfile, Rating
from programmers.services.cloudinary import configure_cloudinary, generate_random_string


class ProgrammerListView(ListView):
    creators_ids = [1, 2, 3]
    queryset = ProgrammerProfile.objects.all()
    template_name = 'programmers/programmers_list.html'
    context_object_name = 'programmers'

    def get_queryset(self):
        queryset = ProgrammerFilter(self.request.GET, queryset=self.queryset).qs
        current_user = self.request.user
        queryset = queryset.exclude(id=current_user.id)

        return queryset

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['form'] = ProgrammerFilter.form
        context['creators'] = self.creators_ids

        if 'experience' in self.request.GET:
            context['experience'] = self.request.GET['experience']

        if 'programming_languages__contains' in self.request.GET:
            context['programming_languages'] = self.request.GET['programming_languages__contains']

        if 'tech_stack__contains' in self.request.GET:
            context['tech_stack'] = self.request.GET['tech_stack__contains']

        if 'wage_min' in self.request.GET:
            context['wage_min'] = self.request.GET['wage_min']

        if 'wage_max' in self.request.GET:
            context['wage_max'] = self.request.GET['wage_max']

        if 'first_name' in self.request.GET:
            context['first_name'] = self.request.GET['first_name']

        if 'last_name' in self.request.GET:
            context['last_name'] = self.request.GET['last_name']

        for programmer in context['programmers']:
            programmer.count = programmer.ratings_count()

        return context


@login_required(login_url="/accounts/login/")
def programmer_detail(request, id):
    rated = False
    user = request.user
    try:
        programmer = get_object_or_404(ProgrammerProfile, id=id)
        programmer.average_rating = programmer.average_rating()
        users_ratings = Rating.objects.filter(user_id=request.user.id, programmer_id=id).first()
        programmer.count = programmer.ratings_count()
        if users_ratings:
            rated = True
            programmer.count = programmer.ratings_count()
    except ProgrammerProfile.DoesNotExist:
        return HttpResponseNotFound("Page not found")
    if request.user.id == programmer.user_id.id:
        owner = True
    else:
        owner = False

    ctx = {
        "programmer": programmer,
        "user": user,
        "rated": rated,
        "owner": owner,
    }

    return render(
        request,
        template_name="programmers/programmer_detail.html",
        context=ctx,
    )


@login_required(login_url="/accounts/login/")
def programmer_create_form(request):
    user_id = request.user.id
    programmer_profile_exists = ProgrammerProfile.objects.filter(user_id=user_id).exists()
    if programmer_profile_exists:
        return HttpResponseForbidden("You have already created a programmer account")
    form = ProgrammerCreationModelForm(request.POST or None)
    if request.method == 'GET':
        ctx = {
            "form": form,
        }
        return render(
            request,
            template_name='programmers/programmer_create_model_form.html',
            context=ctx,
        )

    elif request.method == 'POST':
        form = ProgrammerCreationModelForm(request.POST)
        if form.is_valid():
            programmer = form.save(commit=False)
            programmer.user_id = request.user
            programmer.save()
            request.user.is_dev = True
            request.user.save()
            messages.success(
                request,
                message=f"Programmer {programmer.user_id.first_name} {programmer.user_id.last_name} has been successfully created",
            )

            return redirect(f'/programmers/myprofile/{user_id}')
        ctx = {
            "form": form,
        }
        messages.error(
            request,
            message="Something went wrong",
        )
        return render(
            request,
            template_name='programmers/programmer_create_model_form.html',
            context=ctx,
        )


@login_required(login_url="/accounts/login/")
def programmer_update_model_form(request, id):
    programmer = get_object_or_404(ProgrammerProfile, id=id)
    user = request.user

    if request.user.id == programmer.user_id.id:
        owner = True
    else:
        owner = False
        raise PermissionDenied("You do not have permission to edit this index.")

    if request.method == "GET":
        form = ProgrammerCreationModelForm(instance=programmer)
        ctx = {
            "form": form,
            "user": user,
            'owner': owner,
            "programmer": programmer,
        }
        return render(
            request,
            template_name="programmers/programmer_update_model_form.html",
            context=ctx,
        )
    if request.method == "POST":
        form = ProgrammerCreationModelForm(request.POST, instance=programmer)

        if form.is_valid():
            form.save()
            ctx = {
                "form": form,
                "user": user,
                'owner': owner,
                "programmer": programmer,
            }
            messages.success(
                request,
                message=f"Programmer {programmer.user_id.first_name} {programmer.user_id.last_name} has been successfully edited",
            )
            return render(
                request,
                template_name="programmers/my_profile.html",
                context=ctx,
            )

        ctx = {
            "form": form,
            "user": user,
            "programmer": programmer,
        }
        messages.error(
            request,
            message="Something went wrong",
        )

        return render(
            request,
            template_name="programmers/programmer_update_model_form.html",
            context=ctx,
        )


@login_required(login_url="/accounts/login/")
def programmer_delete_confirm(request, id):
    programmer = get_object_or_404(ProgrammerProfile, id=id)
    programmer.count = programmer.ratings_count()
    user = request.user

    if request.user.id != programmer.user_id.id:
        raise PermissionDenied("You do not have permission to delete this index.")
    if request.method == "GET":
        ctx = {
            "programmer": programmer,
            "user": user,
        }
        return render(
            request,
            template_name="programmers/programmer_delete_confirm.html",
            context=ctx,
        )

    if request.method == "POST":
        programmer.delete()
        request.user.is_dev = False
        request.user.save()
        messages.success(
            request,
            message=f"Programmer {programmer.user_id.first_name} {programmer.user_id.last_name} has been successfully deleted",
        )

        return redirect("my_profile", id=user.id)


@login_required(login_url="/accounts/login/")
def rate_programmer(request, id):
    programmer = get_object_or_404(ProgrammerProfile, id=id)

    if request.method == "GET":
        user = request.user
        if user.id == programmer.user_id.id:
            raise PermissionDenied("You cannot rate yourself.")
        rating_exists = Rating.objects.filter(programmer=programmer, user=user).first()
        if rating_exists:
            form = RatingForm(initial={'rating': rating_exists.rating})
        else:
            form = RatingForm()
        ctx = {
            "programmer": programmer,
            "form": form,
        }
        return render(
            request,
            template_name='programmers/rate_programmer.html',
            context=ctx,
        )

    if request.method == 'POST':
        form = RatingForm(request.POST)
        user = request.user

        if form.is_valid():
            user_rating = form.cleaned_data['rating']
            rating_exists = Rating.objects.filter(programmer=programmer, user=user).first()
            if rating_exists:
                rating_exists.rating = user_rating
                rating_exists.save()
                messages.success(
                    request,
                    message="Your rating has been updated."
                )
            else:
                new_rating = Rating.objects.create(programmer=programmer, user=user, rating=user_rating)
                new_rating.save()
                messages.success(
                    request,
                    message="Your rating has been submitted.",
                )

            rated = False
            try:
                programmer = get_object_or_404(ProgrammerProfile, id=id)
                programmer.average_rating = programmer.average_rating()
                programmer.count = programmer.ratings_count()
                users_ratings = Rating.objects.filter(user_id=user.id, programmer_id=id).first()
                if users_ratings:
                    rated = True
            except ProgrammerProfile.DoesNotExist:
                return HttpResponseNotFound("Page not found")

            ctx = {
                "form": form,
                "programmer": programmer,
                "user": user,
                "rated": rated,
            }

            return render(
                request,

knownProgrammer/programmers/templates/programmers/programmer_avatar_update.html
{% extends "accounts/base.html" %}

{% block title %}
    Upload New Avatar
{% endblock title %}

{% block body %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header text-center">
                        <h4 class="card-title">Upload new avatar</h4>
                    </div>
                    {% if messages %}
                        <div class="col-12">
                            <ul class="list-unstyled mb-5">
                                {% for message in messages %}
                                    <li class="alert alert-info">{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    {% if error %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <br>
                    <div class="d-grid gap-2">
                        <form method="POST" action="{% url 'restore_avatar' user.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-danger btn-block">Restore default avatar
                            </button>
                        </form>
                    </div>
                    <div class="card-body text-center">
                        <h5>Actual avatar:</h5>
                        <img src="{{ user.avatar }}" alt="User Avatar">
                        <br><br>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.avatar }}
                            <button type="submit" class="btn btn-outline-primary">Upload</button>
                        </form>
                    </div>

                    <div class="card-footer text-center">
                        <div class="d-grid gap-2">
                            <a href="{% url 'my_profile' user.id %}"
                               class="btn btn-outline-secondary btn-block">Return</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

knownProgrammer/programmers/templates/programmers/programmers_list.html
{% extends "accounts/base.html" %}
{% load stars %}
{% load static %}

{% block title %}
    Programmers List
{% endblock title %}

{% block body %}
    <div class="p-3 mb-2 bg-white text-black">


        <div class="container mt-5">
            <div class="row">

                {% if messages %}
                    <div class="col-12">
                        <ul class="list-unstyled mb-5">
                            {% for message in messages %}
                                <li class="alert alert-info">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <form method="get" action="{% url 'programmers_list' %}">
                    <div class="container">

                        <div class="row mb-3">
                            <div class="col">
                                <label for="id_experience" class="form-label">Experience:</label>
                                <select name="experience" id="id_experience" class="form-select">
                                    <option value="{{ experience }}" selected>{{ experience }}</option>
                                    <option value="Mid">Mid</option>
                                    <option value="Junior">Junior</option>
                                    <option value="Senior">Senior</option>
                                </select>
                            </div>
                            <div class="col">
                                <label for="id_programming_languages__contains" class="form-label">Programming
                                    languages:</label>
                                <select name="programming_languages__contains" id="id_programming_languages__contains"
                                        class="form-select">
                                    <option value="{{ programming_languages }}"
                                            selected>{{ programming_languages }}</option>
                                    <option value="JavaScript">JavaScript</option>

                                    <option value="Python">Python</option>

                                    <option value="Java">Java</option>

                                    <option value="C">C</option>

                                    <option value="C++">C++</option>

                                    <option value="C#">C#</option>

                                    <option value="R">R</option>

                                    <option value="PHP">PHP</option>

                                    <option value="SQL">SQL</option>

                                    <option value="RUST">RUST</option>

                                    <option value="Kotlin">Kotlin</option>

                                    <option value="HTML">HTML</option>

                                    <option value="CSS">CSS</option>

                                    <option value="TypeScript">TypeScript</option>

                                    <option value="Scala">Scala</option>

                                    <option value="SWIFT">SWIFT</option>
                                </select>
                            </div>
                            <div class="col">
                                <label for="id_tech_stack__contains" class="form-label">Tech stack:</label>
                                <select name="tech_stack__contains" id="id_tech_stack__contains" class="form-select">
                                    <option value="{{ tech_stack }}" selected>{{ tech_stack }}</option>
                                    <option value="Django">Django</option>

                                    <option value="Flask">Flask</option>

                                    <option value="FastAPI">FastAPI</option>

                                    <option value="Databases">Databases</option>

                                    <option value="Docker">Docker</option>

                                    <option value="Git | GitHub">Git | GitHub</option>

                                    <option value="Node.js">Node.js</option>

                                    <option value="React">React</option>

                                    <option value="Symphony">Symphony</option>

                                    <option value="Ruby on Rails">Ruby on Rails</option>

                                    <option value="Celery">Celery</option>
                                </select>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col">
                                <label class="form-label">Wage:</label>
                                <div class="input-group">
                                    <input type="text" name="wage_min" id="id_wage_min" class="form-control"
                                           value="{{ wage_min }}">
                                    <span class="input-group-text">-</span>
                                    <input type="text" name="wage_max" id="id_wage_max" class="form-control"
                                           value="{{ wage_max }}">
                                </div>
                            </div>
                            <div class="col">
                                <label for="id_first_name" class="form-label">Name:</label>
                                <input type="text" name="first_name" id="id_first_name" class="form-control"
                                       value="{{ first_name }}">
                            </div>
                            <div class="col">
                                <label for="id_last_name" class="form-label">Last name:</label>
                                <input type="text" name="last_name" id="id_last_name" class="form-control"
                                       value="{{ last_name }}">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <div class="d-grid gap-2 mb-5">
                                    <button type="submit" class="btn btn-outline-primary">Filter</button>
                                </div>
                            </div>
                            <div class="col">
                                <div class="d-grid gap-2 mb-5">
                                    <a href="{% url 'programmers_list' %}" class="btn btn-outline-dark">Reset
                                        filters</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

            <div class="row">

                {% for programmer in programmers %}
                    <div class="col-md-4">

                        <div class="card mb-4 hover-effect {% if programmer.user_id_id in creators %}card-creators{% endif %}">
                            <div class="card-body">
                                <a href="{% url 'programmer_detail' programmer.id %}"
                                   class="text-decoration-none text-reset">
                                    <img src="{{ programmer.user_id.avatar }}" alt="User Avatar"
                                         style="display: block; margin: 0 auto;">
                                    <h4 class="card-title fw-bold text-center">{{ programmer.user_id.first_name }} {{ programmer.user_id.last_name }}</h4>

                                    <div class="rating">
                                        <span class="fw-bold">Rating:</span>
                                        {{ programmer.average_rating|get_rating_stars|safe }}
                                        <span class="ratings"> {{ programmer.count }} rating(s)</span>
                                    </div>

                                    <div class="experience">
                                        <span class="fw-bold">Experience:</span>
                                        <h4 class="fw-bold {% if programmer.experience == "Junior" %}junior{% elif programmer.experience == "Mid" %}mid{% else %}senior{% endif %}">{{ programmer.experience }}</h4>
                                    </div>

                                    <div class="technologies mt-3">
                                        <span class="fw-bold">Programming Languages:</span>

                                        {% for language in programmer.programming_languages %}
                                            <span class="badge bg-success ms-2">{{ language }}</span>
                                        {% empty %}
                                            <span class="fw-italic">No languages listed</span>
                                        {% endfor %}
                                    </div>

                                    <div class="technologies mt-2">
                                        <span class="fw-bold">Tech stack:</span>
                                        {% for framework in programmer.tech_stack %}
                                            <span class="badge bg-secondary ms-2">{{ framework }}</span>
                                        {% empty %}
                                            <span class="fw-italic">No Tech stack listed</span>
                                        {% endfor %}
                                    </div>
                                </a>
                            </div>
                        </div>

                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock body %}

knownProgrammer/programmers/templates/programmers/rate_programmer.html
{% extends 'accounts/base.html' %}
{% load stars %}
{% load static %}

{% block title %}
    Programmer Rate Form
{% endblock title %}

{% block body %}
    {% if messages %}
        <div class="col-12">
            <ul class="list-unstyled mb-5">
                {% for message in messages %}
                    <li class="alert alert-info">{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-header card-title text-center">
                        <h3>{{ programmer.user_id.first_name }} {{ programmer.user_id.last_name }}</h3>
                    </div>
                    <div class="card-body text-center">
                        <form class="mb-4" action="{% url 'rate_programmer' programmer.id %}" method="post">
                            {% csrf_token %}
                            <div class="form-group fw-bold">
                                <label for="id_rating">Choose rating:</label>
                                <div>
                                    {% for choice in form.rating %}
                                        <div>
                                            {{ choice.tag }}
                                            <label for="{{ choice.id_for_label }}" class="star-label">
                                                {{ choice.choice_label|get_rating_stars|safe }}</label>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <br>
                            <div class="d-grid">
                                <button type="submit" class="btn btn-outline-primary">
                                    <span class="d-flex justify-content-center align-items-center">Rate Programmer</span>
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="d-grid">
                            <a href="{% url 'programmer_detail' programmer.id %}"
                               class="btn btn-outline-secondary btn-block">Return</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock body %}

knownProgrammer/programmers/templates/programmers/user_update_model_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>