knownProgrammer/knownProgrammer/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts.views.function_based_views import (
    homepage,
)

urlpatterns = [
    path('', homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('programmers/', include('programmers.urls_programmers')),
    path('accounts/', include('accounts.urls_accounts')),
    path('messages/', include('communication.urls_communication'))
]

knownProgrammer/communication/models.py
from django.db import models
from django.conf import settings


# Create your models here.

class Message(models.Model):
    sent_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sent_by_message')
    sent_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sent_to_message')
    content = models.TextField(max_length=5000, null=False)
    title = models.CharField(max_length=100, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

knownProgrammer/communication/forms.py
from django import forms

from communication.models import Message

class MessageCreationModelForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['title', 'content']

knownProgrammer/communication/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from datetime import datetime

from accounts.models import CustomUser
from communication.forms import MessageCreationModelForm
from communication.models import Message

login_redirect = reverse_lazy("login")

# Create your views here.

def get_last_message(contact, request_user):
    last_message_i_sent_date = Message.objects.filter(sent_by=request_user, sent_to=contact).order_by('created_at').values('created_at').last()
    last_message_i_get_date = Message.objects.filter(sent_to=request_user, sent_by=contact).order_by('created_at').values('created_at').last()
    if last_message_i_sent_date == None:
        return last_message_i_get_date['created_at']
    elif last_message_i_get_date == None:
        return last_message_i_sent_date['created_at']
    else:
        if last_message_i_sent_date['created_at'] > last_message_i_get_date['created_at']:
            return last_message_i_sent_date['created_at']
        else:
            return last_message_i_get_date['created_at']


def get_recipients(recipients_ids:list):
    return {user_id['sent_to']: get_object_or_404(CustomUser, id=user_id['sent_to']) for user_id in recipients_ids}


def get_senders(senders_ids:list):
    return {user_id['sent_by']: get_object_or_404(CustomUser, id=user_id['sent_by']) for user_id in senders_ids}

def delete_contact_duplicates(senders, recipients):
    contacts = []
    for contact in recipients.values():
        contacts.append(contact)

    for contact_id, contact in senders.items():
        if contact_id not in recipients.keys():
            contacts.append(contact)

    return contacts

@login_required(login_url=login_redirect)
def send_message_view(request, id):
    user_profile_exists = CustomUser.objects.filter(id=id).exists()
    if not user_profile_exists:
        raise PermissionDenied("User not found")
    elif request.user.id == id:
        raise PermissionDenied("You can't send message to yourself")
    user_id = request.user.id
    sent_by_user = get_object_or_404(CustomUser, id=user_id)
    sent_to_user = get_object_or_404(CustomUser, id=id)
    form = MessageCreationModelForm
    previous_page = request.META.get('HTTP_REFERER')
    if request.method == "GET":
        ctx = {
            'sent_by_user': sent_by_user,
            'sent_to_user': sent_to_user,
            'form': form,
            'previous_page': previous_page,
        }
        return render(request, template_name="communication/send_message.html", context=ctx)
    if request.method == "POST":
        form = MessageCreationModelForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sent_by = sent_by_user
            message.sent_to = sent_to_user
            message.save()
            messages.success(request, ("Your message has been successfully sent"))
            return redirect('messages_person_list')
        ctx = {
            'sent_by_user': sent_by_user,
            'sent_to_user': sent_to_user,
            'form': form,
            'previous_page': previous_page,
        }
        messages.error(request, ("Something went wrong"))
        return render(request, template_name="communication/send_message.html", context=ctx)

def replay_message_view(request, id):
    previous_message = get_object_or_404(Message, id=id)
    user_profile_exists = CustomUser.objects.filter(id=previous_message.sent_by.id).exists()
    message_exists = Message.objects.filter(id=id).exists()
    if not message_exists:
        raise PermissionDenied("Message not found")
    elif not user_profile_exists:
        raise PermissionDenied("User not found")
    elif request.user.id != previous_message.sent_by.id and request.user.id != previous_message.sent_to.id:
        raise PermissionDenied("You have not permission to replay on this messages")
    user_session_id = request.user.id
    if user_session_id == previous_message.sent_by.id:
        sent_by_user = get_object_or_404(CustomUser, id=user_session_id)
        sent_to_user = get_object_or_404(CustomUser, id=previous_message.sent_to.id)
    else:
        sent_by_user = get_object_or_404(CustomUser, id=user_session_id)
        sent_to_user = get_object_or_404(CustomUser, id=previous_message.sent_by.id)
    form = MessageCreationModelForm
    previous_page = request.META.get('HTTP_REFERER')
    if request.method == "GET":
        ctx = {
            'sent_by_user': sent_by_user,
            'sent_to_user': sent_to_user,
            'form': form,
            'previous_page': previous_page,
            'previous_message': previous_message,
        }
        return render(request, template_name="communication/replay_message.html", context=ctx)
    if request.method == "POST":
        form = MessageCreationModelForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sent_by = sent_by_user
            message.sent_to = sent_to_user
            message.save()
            messages.success(request, ("Your message has been successfully sent"))
            return redirect('messages_person_list')
        ctx = {
            'sent_by_user': sent_by_user,
            'sent_to_user': sent_to_user,
            'form': form,
            'previous_page': previous_page,
            'previous_message': previous_message,
        }
        messages.error(request, ("Something went wrong"))
        return render(request, template_name="communication/replay_message.html", context=ctx)

@login_required(login_url=login_redirect)
def my_messages_people_list_view(request):
    recipients_ids = Message.objects.filter(sent_by=request.user).values('sent_to').distinct()
    senders_ids = Message.objects.filter(sent_to=request.user).values('sent_by').distinct()

    senders = get_senders(senders_ids)
    recipients = get_recipients(recipients_ids)

    contacts = delete_contact_duplicates(senders, recipients)

    contacts_with_date = [[contact, get_last_message(contact, request.user)] for contact in contacts]

    contacts_with_date.sort(key=lambda x: x[1], reverse=True)


    if request.method == 'GET':
        ctx = {
            'contacts': contacts_with_date,
        }
        return render(request, 'communication/my_messages_people_list.html', context=ctx)

@login_required(login_url=login_redirect)
def my_messages_with_correspondent_view(request, id):
    user = get_object_or_404(CustomUser, id=id)
    sent_by_me = Message.objects.filter(sent_by=request.user.id, sent_to=id).order_by('-created_at')
    sent_to_me = Message.objects.filter(sent_by=id, sent_to=request.user.id).order_by('-created_at')

    if request.method == 'GET':
        ctx = {
            'user': user,
            'sent_by_me': sent_by_me,
            'sent_to_me': sent_to_me,
        }
        return render(request, 'communication/my_messages_with_correspondent.html', context=ctx)

@login_required(login_url=login_redirect)
def message_view(request, id):
    message = get_object_or_404(Message, id=id)
    if message.sent_by != request.user and message.sent_to != request.user:
        raise PermissionDenied("You can't see this message")
    if request.method == 'GET':
        ctx = {
            'message': message,
        }
        return render(request, 'communication/message.html', context=ctx)

knownProgrammer/communication/templates/communication/message.html
{% extends 'accounts/base.html' %}
{% block title %}Message{% endblock title %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card my-4">
                <div class="card-header">
                    <h5 class="card-title mb-0">Message Details</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <h6>Sent by:</h6>
                            <img src="{{ message.sent_by.avatar }}" class="img-fluid rounded-circle" alt="Avatar" style="max-width: 50px; height: auto;">
                            <p>{{ message.sent_by.first_name }} {{ message.sent_by.last_name }} ({{ message.sent_by.email }})</p>
                        </div>
                        <div class="col-md-6">
                            <h6>Sent to:</h6>
                            <img src="{{ message.sent_to.avatar }}" class="img-fluid rounded-circle" alt="Avatar" style="max-width: 50px; height: auto;">
                            <p>{{ message.sent_to.first_name }} {{ message.sent_to.last_name }} ({{ message.sent_to.email }})</p>
                        </div>
                    </div>
                    <hr>
                    <h6>Title:</h6>
                    <p>{{ message.title }}</p>
                    <h6>Content:</h6>
                    <p>{{ message.content }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">
                {% if request.user.id == message.sent_to.id %}
                <a href="{% url 'messages_with_list' message.sent_by.id %}" class="btn btn-outline-secondary mt-3">Return</a>
                <a href="{% url 'replay' message.id %}" class="btn btn-outline-primary mt-3 btn-block">Reply</a>
                {% elif request.user.id == message.sent_by.id %}
                <a href="{% url 'messages_with_list' message.sent_to.id %}" class="btn btn-outline-secondary mt-3">Return</a>
                <a href="{% url 'replay' message.id %}" class="btn btn-outline-primary mt-3 btn-block">Send next message</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock body %}

knownProgrammer/communication/templates/communication/my_messages_people_list.html
{% extends 'accounts/base.html' %}
{% block title %}Contacts{% endblock title %}

{% block body %}
{% for message in messages %}
    <li class="alert alert-info">{{ message }}</li>
{% endfor %}
<div class="container mt-4">
    <h2>My conversations:</h2>
    <div class="list-group">
    {% if contacts %}
        {% for person in contacts %}
            <a href="{% url 'messages_with_list' person.0.id  %}" class="list-group-item position-relative">
                <div class="media">
                    <img src="{{ person.0.avatar }}" class="mr-3 rounded-circle" alt="{{ person.0.first_name }} Avatar" style="width: 50px; height: 50px;">
                    <div class="media-body">
                        <h5 class="mt-0 mb-1">{{ person.0.first_name }} {{ person.0.last_name }}</h5>
                        <p class="mb-0">Email: {{ person.0.email }}</p>
                    </div>
                    {% if person.1 %}
                    <div class="position-absolute top-0 end-0 p-2">
                        <small class="text-muted">{{ person.1 }}</small>
                    </div>
                    {% endif %}
                </div>
            </a>
        {% endfor %}
    {% else %}
        <a style="color: #b00414">You haven't sent any messages yet</a>
    {% endif %}
    </div>
    <div class="col-md-12">
        <a href="{% url 'homepage' %}" class="btn btn-outline-secondary mt-3">Return to main page</a>
    </div>
</div>
{% endblock body %}

knownProgrammer/communication/templates/communication/my_messages_person_list.html
{% extends 'accounts/base.html' %}
{% block title %}Contacts{% endblock title %}

{% block body %}
{% for message in messages %}
    <li class="alert alert-info">{{ message }}</li>
{% endfor %}
<div class="container mt-4">
    <h2>My conversations:</h2>
    <div class="list-group">
    {% if contacts %}
        {% for person in contacts %}
            <a href="{% url 'messages_with_list' person.0.id  %}" class="list-group-item position-relative">
                <div class="media">
                    <img src="{{ person.0.avatar }}" class="mr-3 rounded-circle" alt="{{ person.0.first_name }} Avatar" style="width: 50px; height: 50px;">
                    <div class="media-body">
                        <h5 class="mt-0 mb-1">{{ person.0.first_name }} {{ person.0.last_name }}</h5>
                        <p class="mb-0">Email: {{ person.0.email }}</p>
                    </div>
                    {% if person.1 %}
                    <div class="position-absolute top-0 end-0 p-2">
                        <small class="text-muted">{{ person.1.created_at }}</small>
                    </div>
                    {% endif %}
                </div>
            </a>
        {% endfor %}
    {% else %}
        <a style="color: #b00414">You haven't sent any messages yet</a>
    {% endif %}
    </div>
    <div class="col-md-12">
        <a href="{% url 'homepage' %}" class="btn btn-outline-secondary mt-3">Return to main page</a>
    </div>
</div>
{% endblock body %}

knownProgrammer/communication/templates/communication/my_messages_with_correspondent.html
{% extends 'accounts/base.html' %}
{% block title %}My messages with {{ user.first_name }} {{ user.last_name }}{% endblock title %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card my-4">
                <div class="card-header">
                    <h5 class="card-title mb-0">Programmer Information</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-2">
                            <img src="{{ user.avatar }}" class="img-fluid rounded-circle" alt="Avatar">
                        </div>
                        <div class="col-md-10">
                            <p><strong>Name:</strong> {{ user.first_name }} {{ user.last_name }}</p>
                            <p><strong>Email:</strong> {{ user.email }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0">Messages</h5>
                </div>
                <div class="card-body">
                    <h6>Sent by me:</h6>
                    {% if sent_by_me %}
                    <ul class="list-group">
                        {% for message in sent_by_me %}
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col-md-10">
                                        <a>Title: </a><a href="{% url 'message' message.id %}" style="text-decoration: none; font-weight: bold; color: black">{{ message.title }}</a>
                                    </div>
                                    <div class="col-md-2 text-right">
                                        <span>{{ message.created_at }}</span>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                        <a style="color: #b00414">You haven't received any messages yet</a>
                    {% endif %}
                    <h6 class="mt-4">Sent to me:</h6>
                    {% if sent_to_me %}
                    <ul class="list-group">
                        {% for message in sent_to_me %}
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col-md-10">
                                        <a>Title: </a><a href="{% url 'message' message.id %}" style="text-decoration: none; font-weight: bold; color: black">{{ message.title }}</a>
                                    </div>
                                    <div class="col-md-2 text-right">
                                        <span>{{ message.created_at }}</span>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <a style="color: #b00414">You haven't sent any messages yet</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
            <div class="col-md-12">
                <a href="{% url 'messages_person_list' %}" class="btn btn-outline-secondary mt-3">Return to contacts list</a>
            </div>
        </div>
</div>
{% endblock body %}

knownProgrammer/communication/templates/communication/replay_message.html
{% extends 'accounts/base.html' %}
{% block title %}Sending message{% endblock title %}

{% block body %}
{% for message in messages %}
    <li class="alert alert-info">{{ message }}</li>
{% endfor %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card my-4">
                <div class="card-header">
                    <h5 class="card-title mb-0">Message Details</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <h6>Send by:</h6>
                            <img src="{{ sent_by_user.avatar }}" class="rounded-circle" alt="Avatar" style="max-width: 35px; height: auto;">
                            {{ sent_by_user.first_name }} {{ sent_by_user.last_name }}
                        </div>
                        <div class="col-md-6">
                            <h6>Send to:</h6>
                            <img src="{{ sent_to_user.avatar }}" class="rounded-circle" alt="Avatar" style="max-width: 35px; height: auto;">
                            {{ sent_to_user.first_name }} {{ sent_to_user.last_name }}
                        </div>
                    </div>
                    <hr>
                    <form method="post" action="{% url 'send_message' sent_to_user.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_title">Title:</label>
                            <input type="text" class="form-control" id="id_title" name="title" placeholder="Enter title" value="Re: {{ previous_message.title }}">
                        </div>
                        <div class="form-group">
                            <label for="id_contents">Content:</label>
                            <textarea class="form-control" id="id_contents" name="content" rows="3" placeholder="Enter content"></textarea>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-outline-secondary">Send message</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            {% if None == previous_page %}
            <a href="{% url 'programmers_list' %}" class="btn btn-outline-secondary mt-3">Return to Programmers list</a>
            {% else %}
            <a href="{{ previous_page }}" class="btn btn-outline-secondary mt-3">Return</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock body %}

knownProgrammer/communication/templates/communication/send_message.html
{% extends 'accounts/base.html' %}
{% block title %}Sending message{% endblock title %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card my-4">
                <div class="card-header">
                    <h5 class="card-title mb-0">Message Details</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <h6>Send by:</h6>
                            <img src="{{ sent_by_user.avatar }}" class="rounded-circle" alt="Avatar" style="max-width: 35px; height: auto;">
                            {{ sent_by_user.first_name }} {{ sent_by_user.last_name }}
                        </div>
                        <div class="col-md-6">
                            <h6>Send to:</h6>
                            <img src="{{ sent_to_user.avatar }}" class="rounded-circle" alt="Avatar" style="max-width: 35px; height: auto;">
                            {{ sent_to_user.first_name }} {{ sent_to_user.last_name }}
                        </div>
                    </div>
                    <hr>
                    <form method="post" action="{% url 'send_message' sent_to_user.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_title">Title:</label>
                            <input type="text" class="form-control" id="id_title" name="title" placeholder="Enter title">
                        </div>
                        <div class="form-group">
                            <label for="id_contents">Contents:</label>
                            <textarea class="form-control" id="id_contents" name="contents" rows="3" placeholder="Enter contents"></textarea>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-outline-secondary">Send message</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <a href="{{ previous_page }}" class="btn btn-outline-secondary mt-3">Return</a>
        </div>
    </div>
</div>
{% endblock body %}